export const usersSeed = [
  {
    name: "Ahri",
    email: "ahri@example.com",
    password: "Foxfire123!",
    NIN: "33.333.333",
    phone: "+573001234569",
    address: "Vastaya Village, Ionia",
    country: "Ionia",
    city: "Ionia City",
    role: "user",
  },
  {
    name: "Lux",
    email: "lux@example.com",
    password: "Lightbringer123!",
    NIN: "44.444.444",
    phone: "+573001234570",
    address: "Demacia Castle, Demacia",
    country: "Demacia",
    city: "Demacia City",
    role: "admin",
  },
  {
    name: "Garen",
    email: "garen@example.com",
    password: "DemacianJustice123!",
    NIN: "55.555.555",
    phone: "+573001234571",
    address: "Demacia Barracks, Demacia",
    country: "Demacia",
    city: "Demacia City",
    role: "user",
  },
  {
    name: "Jinx",
    email: "jinx@example.com",
    password: "PowPow123!",
    NIN: "66.666.666",
    phone: "+573001234572",
    address: "Zaun Underground, Zaun",
    country: "Zaun",
    city: "Zaun City",
    role: "user",
  },
  {
    name: "Zed",
    email: "zed@example.com",
    password: "Shadow123!",
    NIN: "77.777.777",
    phone: "+573001234573",
    address: "Order of the Shadow, Ionia",
    country: "Ionia",
    city: "Ionia City",
    role: "user",
  },
];
