export const usersSeed = [
  {
    name: "Superadmin Filomeno",
    email: "superadmin@gmail.com",
    password: "Superadmin123$",
    NIN: "33.333.333",
    phone: "+573001234569",
    address: "Vastaya Village, Ionia",
    country: "Ionia",
    city: "Ionia City",
    role: "superadmin",
  },
  {
    name: "Admin Chencho",
    email: "admin@gmail.com",
    password: "Admin123$",
    NIN: "44.444.444",
    phone: "+573001234570",
    address: "Demacia Castle, Demacia",
    country: "Demacia",
    city: "Demacia City",
    role: "admin",
  },
  {
    name: "Carrier Romelio",
    email: "carrier@gmail.com",
    password: "Carrier123$",
    NIN: "55.555.555",
    phone: "+573001234571",
    address: "Demacia Barracks, Demacia",
    country: "Demacia",
    city: "Demacia City",
    role: "carrier",
  },
  {
    name: "Pepito",
    email: "pepito@gmail.com",
    password: "Pepito123$",
    NIN: "66.666.666",
    phone: "+573001234572",
    address: "Zaun Underground, Zaun",
    country: "Zaun",
    city: "Zaun City",
    role: "user",
  },
  {
    name: "Pepita",
    email: "pepita@gmail.com",
    password: "Pepita123$",
    NIN: "77.777.777",
    phone: "+573001234573",
    address: "Order of the Shadow, Ionia",
    country: "Ionia",
    city: "Ionia City",
    role: "user",
  },
  {
    name: "Pepitin",
    email: "pepitin@gmail.com",
    password: "Pepitin123$",
    NIN: "77.777.778",
    phone: "+573001234578",
    address: "Order of the Shadow, Ionia",
    country: "Ionia",
    city: "Ionia City",
    role: "user",
  },
  {
    name: "Pepeton",
    email: "pepeton@gmail.com",
    password: "Pepeton123$",
    NIN: "77.777.756",
    phone: "+573001239073",
    address: "Order of the Shadow, Ionia",
    country: "Ionia",
    city: "Ionia City",
    role: "user",
  },
];
