import { createProductDto } from "src/modules/products/createProduct.dto";

export const productsSeed = [
  {
    name: "Porciones papa criolla",
    description: "Deliciosas porciones de papa criolla con un toque especial.",
    price: 4.7,
    img: "https://images.pexels.com/photos/1439177/pexels-photo-1439177.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","PAPAS","VEGETARIANOS"],
  },
  {
    name: "Porciones papa francesa cuatro 7",
    description:
      "Crujientes porciones de papa francesa con un toque de especias.",
    price: 4.7,
    img: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","PAPAS","VEGETARIANOS"],
  },
  {
    name: "Porciones arroz chorizo de cerdo 6",
    description:
      "Sabroso arroz acompañado de chorizo de cerdo, una combinación perfecta.",
    price: 6,
    img: "https://img.freepik.com/fotos-gratis/arroz-verduras-verduras-dos-salchichas_183587-2482.jpg",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones tocineta ahumada 4.8",
    description:
      "Tocineta ahumada con un sabor inigualable, ideal como acompañamiento.",
    price: 4.8,
    img: "https://img.freepik.com/fotos-gratis/coccion-jamon-selva-negra-sarten-fondo-negro-vista-superior_89816-34979.jpg",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones carne desmechada 8.5",
    description:
      "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
    price: 8.5,
    img: "https://images.pexels.com/photos/5737377/pexels-photo-5737377.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones pollo desmechado 8",
    description:
      "Pollo desmechado sazonado y cocinado a la perfección, irresistible.",
    price: 8,
    img: "https://img.freepik.com/foto-gratis/pollo-asado-verduras-mixtas-stir-fry_1339-5344.jpg",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones jamón 9",
    description:
      "Jamón de calidad premium, ideal para los amantes del sabor auténtico.",
    price: 9,
    img: "https://images.pexels.com/photos/4871277/pexels-photo-4871277.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones guacamole 3",
    description: "Guacamole fresco y cremoso, un clásico que no puede faltar.",
    price: 3,
    img: "https://images.pexels.com/photos/5737254/pexels-photo-5737254.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","VEGETARIANOS"],
  },
  {
    name: "Porciones ejote 2.9",
    description:
      "Ejotes frescos y nutritivos, una opción saludable y deliciosa.",
    price: 2.9,
    img: "https://images.pexels.com/photos/1860193/pexels-photo-1860193.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","VEGETARIANOS"],
  },
  {
    name: "Porciones queso mozzarella 4",
    description:
      "Queso mozzarella derretido sobre tus platillos favoritos, simplemente irresistible.",
    price: 4,
    img: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","OTROS","VEGETARIANOS"],
  },
  {
    name: "Porciones yuca 4.7",
    description:
      "Yuca dorada y crujiente, perfecta como acompañamiento o plato principal.",
    price: 4.7,
    img: "https://img.freepik.com/foto-gratis/composicion-raices-yuca-nutritivas-rodajas_23-2149091053.jpg",
    available: true,
    stock: 10,
    category: ["PORCIONES","VEGETARIANOS"],
  },
  { 
    name: "Jugos naturales",
    description: "Refrescantes jugos naturales recién exprimidos.",
    price: 7,
    img: "https://images.pexels.com/photos/7656388/pexels-photo-7656388.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","JUGOS","NO ALCOHOLICAS"],
  },
  {
    name: "Gaseosas de 355 ml",
    description:
      "Gaseosas en presentación de 355 ml, perfectas para acompañar.",
    price: 4,
    img: "https://images.pexels.com/photos/3819969/pexels-photo-3819969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS", "GASEOSAS", "NO ALCOHOLICAS"],
  },
  {
    name: "Gaseosa no retornable",
    description: "Gaseosa no retornable en variedad de sabores.",
    price: 4.3,
    img: "https://images.pexels.com/photos/6696896/pexels-photo-6696896.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","GASEOSAS","NO ALCOHOLICAS"],
  },
  {
    name: "Botella de agua",
    description: "Agua purificada embotellada, ideal para hidratarse.",
    price: 4,
    img: "https://images.pexels.com/photos/7765745/pexels-photo-7765745.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","NO ALCOHOLICAS","OTROS"],
  },
  {
    name: "Té",
    description: "Té caliente o frío según tu preferencia.",
    price: 4,
    img: "https://images.pexels.com/photos/15435876/pexels-photo-15435876/free-photo-of-taza-copa-beber-bebida.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","NO ALCOHOLICAS","OTROS"],
  },
  {
    name: "Cerveza nacional",
    description: "Cerveza nacional de calidad, perfecta para disfrutar.",
    price: 5.4,
    img: "https://images.pexels.com/photos/1672304/pexels-photo-1672304.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","ALCOHOLICAS"],
  },
  {
    name: "Cerveza importada",
    description: "Cerveza importada con sabores únicos de todo el mundo.",
    price: 8.5,
    img: "https://images.pexels.com/photos/2286972/pexels-photo-2286972.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","ALCOHOLICAS"],
  },
  {
    name: "Cola y Pola",
    description: "Refrescante combinación de cola y pola en una sola bebida.",
    price: 5.4,
    img: "https://images.pexels.com/photos/8879617/pexels-photo-8879617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","ALCOHOLICAS"],
  },
  {
    name: "Limonada natural",
    description: "Limonada fresca y natural, perfecta para cualquier ocasión.",
    price: 5.2,
    img: "https://images.pexels.com/photos/5946727/pexels-photo-5946727.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","LIMONADAS", "NO ALCOHOLICAS"],
  },
  {
    name: "Limonada de hierbabuena",
    description: "Limonada con un toque refrescante de hierbabuena.",
    price: 5.9,
    img: "https://images.pexels.com/photos/1187766/pexels-photo-1187766.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","LIMONADAS", "NO ALCOHOLICAS"],
  },
  {
    name: "Cerezada",
    description: "Refrescante bebida de cereza, dulce y deliciosa.",
    price: 7.2,
    img: "https://images.pexels.com/photos/16961742/pexels-photo-16961742/free-photo-of-beber-bebida-vaso-cristal.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","JUGOS", "NO ALCOHOLICAS"],
  },
  {
    name: "Coco",
    description: "Bebida de coco refrescante y exótica.",
    price: 7.5,
    img: "https://images.pexels.com/photos/14346291/pexels-photo-14346291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS", "NO ALCOHOLICAS","JUGOS"],
  },
  {
    name: "Mango biche",
    description: "Bebida de mango biche, dulce y llena de sabor tropical.",
    price: 7.2,
    img: "https://images.pexels.com/photos/10836604/pexels-photo-10836604.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS", "NO ALCOHOLICAS","JUGOS"],
  },
  {
    name: "Chorizo Tijuano",
    description: "Delicioso chorizo Tijuano con sabores intensos y picantes.",
    price: 9.6,
    img: "https://images.pexels.com/photos/15476366/pexels-photo-15476366/free-photo-of-comida-delicioso-sabroso-salchicha.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","CARNES"],
  },
  {
    name: "Chapulines",
    description:
      "Exóticos chapulines crujientes, un manjar tradicional mexicano.",
    price: 8.5,
    img: "https://images.pexels.com/photos/19468702/pexels-photo-19468702/free-photo-of-comida-pimientos-plato-guindilla.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","OTROS","CARNES"],
  },
  {
    name: "Chinicuiles",
    description: "Gusanos de maguey con un sabor único y textura crujiente.",
    price: 9.9,
    img: "https://i.pinimg.com/736x/cc/9d/3b/cc9d3bd3cb0187ec7b89e9b16fa39813.jpg",
    available: true,
    stock: 10,
    category: ["ENTRADAS","OTROS","CARNES"],
  },
  {
    name: "Ensalada hawaiana",
    description: "Ensalada fresca con sabores tropicales y aderezo ligero.",
    price: 5.5,
    img: "https://i.pinimg.com/564x/73/cb/d4/73cbd40a6b6ca602a41679b3f1d979b4.jpg",
    available: true,
    stock: 10,
    category: ["ENTRADAS","ENSALADAS","VEGETARIANOS"],
  },
  {
    name: "Ensalada mexicana",
    description:
      "Ensalada tradicional mexicana con ingredientes frescos y coloridos.",
    price: 6.6,
    img: "https://i.pinimg.com/564x/62/57/01/6257011f20d7063e85da11fed5514fd6.jpg",
    available: true,
    stock: 10,
    category: ["ENTRADAS","ENSALADAS","VEGETARIANOS"],
  },
  {
    name: "Nacho tradicional",
    description: "Nachos crujientes cubiertos con queso fundido y jalapeños.",
    price: 10.5,
    img: "https://i.pinimg.com/564x/00/6c/93/006c93175db59a77152dcd3c20cbe715.jpg",
    available: true,
    stock: 10,
    category: ["ENTRADAS","VEGETARIANOS"],
  },
  {
    name: "Elotes",
    description: "Elotes tiernos con mayonesa, queso y chile en polvo.",
    price: 9.9,
    img: "https://i.pinimg.com/564x/82/53/b7/8253b7964da9d86867085a815e754bae.jpg",
    available: true,
    stock: 10,
    category: ["ENTRADAS","VEGETARIANOS"],
  },
  {
    name: "Longaniza con arepa de queso",
    description: "Longaniza jugosa acompañada de una arepa rellena de queso.",
    price: 8.5,
    img: "https://i.pinimg.com/564x/3a/af/2a/3aaf2ad1c330d07d2d12873b8b500e4a.jpg",
    available: true,
    stock: 10,
    category: ["ENTRADAS","CARNES"],
  },
  {
    name: "Burrito chili",
    description:
      "Burrito relleno de carne de chili con frijoles y queso fundido.",
    price: 16.5,
    img: "https://i.pinimg.com/564x/d9/3f/bd/d93fbd6cec474b7dc38f90c5f84d2b3f.jpg",
    available: true,
    stock: 10,
    category: ["BURRITOS","CARNES"],
  },
  {
    name: "Burrito montañero",
    description: "Burrito sencillo pero sabroso, con carne, arroz y frijoles.",
    price: 3,
    img: "https://i.pinimg.com/564x/de/3d/94/de3d9425cd7b0e32359d0241d411d40b.jpg",
    available: true,
    stock: 10,
    category: ["BURRITOS","CARNES"],
  },
  {
    name: "Churrasco",
    description: "Jugoso churrasco a la parrilla con acompañamientos gourmet.",
    price: 30.9,
    img: "https://i.pinimg.com/564x/5f/d7/2b/5fd72b36386459b3693cbb5583777b16.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Punta de anca",
    description:
      "Punta de anca asada a la perfección con guarniciones especiales.",
    price: 32.5,
    img: "https://i.pinimg.com/564x/5b/f8/8e/5bf88e5712c3658669f86acfdb6f1ba4.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Parrilla mixta",
    description: "Variedad de carnes en una deliciosa parrilla mixta gourmet.",
    price: 31.8,
    img: "https://i.pinimg.com/564x/5d/b9/14/5db914c81f82d56eef3040172e44b5d5.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Filet migñon",
    description: "Filet migñon tierno y jugoso con salsa especial.",
    price: 33.9,
    img: "https://i.pinimg.com/564x/2e/26/c1/2e26c17261ceb6a2f4037cc6bc4bbb38.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Chuleta de cerdo",
    description: "Chuleta de cerdo a la parrilla con adobo casero.",
    price: 26.9,
    img: "https://i.pinimg.com/564x/7d/8e/c3/7d8ec3d9cd064b35120e00763ea489fe.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga en salsa de champiñones",
    description: "Pechuga de pollo con salsa cremosa de champiñones.",
    price: 28.9,
    img: "https://i.pinimg.com/564x/51/49/8f/51498fd136a444dc9a64792e1add887d.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga a la brasa",
    description: "Pechuga de pollo asada a la brasa con especias aromáticas.",
    price: 26.5,
    img: "https://i.pinimg.com/736x/9a/24/47/9a24477b58a33f1c8ae8e6dd0eadb050.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga gratinada",
    description: "Pechuga de pollo gratinada con queso derretido y hierbas.",
    price: 28.9,
    img: "https://i.pinimg.com/564x/06/b2/a7/06b2a765eb9efb56179ea1093eceb5dc.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga hawaiana",
    description: "Pechuga de pollo con salsa agridulce y piña asada.",
    price: 29.9,
    img: "https://i.pinimg.com/564x/f6/7d/16/f67d16c4a15316657d697319fc210d38.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Trucha al ajillo",
    description: "Trucha fresca preparada al ajillo con hierbas y limón.",
    price: 27.7,
    img: "https://i.pinimg.com/564x/65/35/57/653557c0e284e285c00318d9de1ccfb3.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES","PESCADOS"],
  },
  {
    name: "Trucha gratinada",
    description: "Trucha asada con queso gratinado y especias mediterráneas.",
    price: 29,
    img: "https://i.pinimg.com/564x/ec/15/0e/ec150ed7894577d19291ea89170f51a2.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES","PESCADOS"],
  },
  {
    name: "Picada",
    description: "Exquisita picada de carnes con acompañamientos variados.",
    price: 35.5,
    img: "https://i.pinimg.com/564x/b7/76/db/b776db888b370ca67325d212688173e0.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Picada Don Chily",
    description:
      "Generosa picada con una selección premium de carnes y quesos.",
    price: 57,
    img: "https://i.pinimg.com/564x/08/07/1b/08071b0c8209e0e61faa751cedfc3c9c.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES","OTROS"],
  },
  {
    name: "Ensalada Doña Florinda",
    description:
      "Ensalada fresca con ingredientes gourmet y aderezo exclusivo.",
    price: 19.9,
    img: "https://i.pinimg.com/564x/4b/dc/c0/4bdcc0dce5141170f8bbbcdb562bbdf0.jpg",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","VEGETARIANOS","ENSALADAS"],
  },
];
