import { createProductDto } from "src/modules/products/createProduct.dto";

export const productsSeed = [
  {
    name: "Porciones papa criolla",
    description: "Deliciosas porciones de papa criolla con un toque especial.",
    price: 4.7,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","PAPAS","VEGETARIANOS"],
  },
  {
    name: "Porciones papa francesa cuatro 7",
    description:
      "Crujientes porciones de papa francesa con un toque de especias.",
    price: 4.7,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","PAPAS","VEGETARIANOS"],
  },
  {
    name: "Porciones arroz chorizo de cerdo 6",
    description:
      "Sabroso arroz acompañado de chorizo de cerdo, una combinación perfecta.",
    price: 6,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones tocineta ahumada 4.8",
    description:
      "Tocineta ahumada con un sabor inigualable, ideal como acompañamiento.",
    price: 4.8,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones carne desmechada 8.5",
    description:
      "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
    price: 8.5,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones pollo desmechado 8",
    description:
      "Pollo desmechado sazonado y cocinado a la perfección, irresistible.",
    price: 8,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones jamón 9",
    description:
      "Jamón de calidad premium, ideal para los amantes del sabor auténtico.",
    price: 9,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","CARNES"],
  },
  {
    name: "Porciones guacamole 3",
    description: "Guacamole fresco y cremoso, un clásico que no puede faltar.",
    price: 3,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","VEGETARIANOS"],
  },
  {
    name: "Porciones ejote 2.9",
    description:
      "Ejotes frescos y nutritivos, una opción saludable y deliciosa.",
    price: 2.9,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","VEGETARIANOS"],
  },
  {
    name: "Porciones queso mozzarella 4",
    description:
      "Queso mozzarella derretido sobre tus platillos favoritos, simplemente irresistible.",
    price: 4,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","OTROS","VEGETARIANOS"],
  },
  {
    name: "Porciones yuca 4.7",
    description:
      "Yuca dorada y crujiente, perfecta como acompañamiento o plato principal.",
    price: 4.7,
    img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PORCIONES","VEGETARIANOS"],
  },
  {
    name: "Jugos naturales",
    description: "Refrescantes jugos naturales recién exprimidos.",
    price: 7,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","JUGOS","NO ALCOHOLICAS"],
  },
  {
    name: "Gaseosas de 355 ml",
    description:
      "Gaseosas en presentación de 355 ml, perfectas para acompañar.",
    price: 4,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS", "GASEOSAS", "NO ALCOHOLICAS"],
  },
  {
    name: "Gaseosa no retornable",
    description: "Gaseosa no retornable en variedad de sabores.",
    price: 4.3,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","GASEOSAS","NO ALCOHOLICAS"],
  },
  {
    name: "Botella de agua",
    description: "Agua purificada embotellada, ideal para hidratarse.",
    price: 4,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","NO ALCOHOLICAS","OTROS"],
  },
  {
    name: "Té",
    description: "Té caliente o frío según tu preferencia.",
    price: 4,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","NO ALCOHOLICAS","OTROS"],
  },
  {
    name: "Cerveza nacional",
    description: "Cerveza nacional de calidad, perfecta para disfrutar.",
    price: 5.4,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","ALCOHOLICAS"],
  },
  {
    name: "Cerveza importada",
    description: "Cerveza importada con sabores únicos de todo el mundo.",
    price: 8.5,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","ALCOHOLICAS"],
  },
  {
    name: "Cola y Pola",
    description: "Refrescante combinación de cola y pola en una sola bebida.",
    price: 5.4,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","ALCOHOLICAS"],
  },
  {
    name: "Limonada natural",
    description: "Limonada fresca y natural, perfecta para cualquier ocasión.",
    price: 5.2,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","LIMONADAS", "NO ALCOHOLICAS"],
  },
  {
    name: "Limonada de hierbabuena",
    description: "Limonada con un toque refrescante de hierbabuena.",
    price: 5.9,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","LIMONADAS", "NO ALCOHOLICAS"],
  },
  {
    name: "Cerezada",
    description: "Refrescante bebida de cereza, dulce y deliciosa.",
    price: 7.2,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS","JUGOS", "NO ALCOHOLICAS"],
  },
  {
    name: "Coco",
    description: "Bebida de coco refrescante y exótica.",
    price: 7.5,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS", "NO ALCOHOLICAS","JUGOS"],
  },
  {
    name: "Mango biche",
    description: "Bebida de mango biche, dulce y llena de sabor tropical.",
    price: 7.2,
    img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BEBIDAS", "NO ALCOHOLICAS","JUGOS"],
  },
  {
    name: "Chorizo Tijuano",
    description: "Delicioso chorizo Tijuano con sabores intensos y picantes.",
    price: 9.6,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","CARNES"],
  },
  {
    name: "Chapulines",
    description:
      "Exóticos chapulines crujientes, un manjar tradicional mexicano.",
    price: 8.5,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","OTROS","CARNES"],
  },
  {
    name: "Chinicuiles",
    description: "Gusanos de maguey con un sabor único y textura crujiente.",
    price: 9.9,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","OTROS","CARNES"],
  },
  {
    name: "Ensalada hawaiana",
    description: "Ensalada fresca con sabores tropicales y aderezo ligero.",
    price: 5.5,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","ENSALADAS","VEGETARIANOS"],
  },
  {
    name: "Ensalada mexicana",
    description:
      "Ensalada tradicional mexicana con ingredientes frescos y coloridos.",
    price: 6.6,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","ENSALADAS","VEGETARIANOS"],
  },
  {
    name: "Nacho tradicional",
    description: "Nachos crujientes cubiertos con queso fundido y jalapeños.",
    price: 10.5,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","VEGETARIANOS"],
  },
  {
    name: "Elotes",
    description: "Elotes tiernos con mayonesa, queso y chile en polvo.",
    price: 9.9,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","VEGETARIANOS"],
  },
  {
    name: "Longaniza con arepa de queso",
    description: "Longaniza jugosa acompañada de una arepa rellena de queso.",
    price: 8.5,
    img: "https://images.pexels.com/photos/4577740/pexels-photo-4577740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["ENTRADAS","CARNES"],
  },
  {
    name: "Burrito chili",
    description:
      "Burrito relleno de carne de chili con frijoles y queso fundido.",
    price: 16.5,
    img: "https://images.pexels.com/photos/2955819/pexels-photo-2955819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BURRITOS","CARNES"],
  },
  {
    name: "Burrito montañero",
    description: "Burrito sencillo pero sabroso, con carne, arroz y frijoles.",
    price: 3,
    img: "https://images.pexels.com/photos/2955819/pexels-photo-2955819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["BURRITOS","CARNES"],
  },
  {
    name: "Churrasco",
    description: "Jugoso churrasco a la parrilla con acompañamientos gourmet.",
    price: 30.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Punta de anca",
    description:
      "Punta de anca asada a la perfección con guarniciones especiales.",
    price: 32.5,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Parrilla mixta",
    description: "Variedad de carnes en una deliciosa parrilla mixta gourmet.",
    price: 31.8,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Filet migñon",
    description: "Filet migñon tierno y jugoso con salsa especial.",
    price: 33.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Chuleta de cerdo",
    description: "Chuleta de cerdo a la parrilla con adobo casero.",
    price: 26.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga en salsa de champiñones",
    description: "Pechuga de pollo con salsa cremosa de champiñones.",
    price: 28.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga a la brasa",
    description: "Pechuga de pollo asada a la brasa con especias aromáticas.",
    price: 26.5,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga gratinada",
    description: "Pechuga de pollo gratinada con queso derretido y hierbas.",
    price: 28.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Pechuga hawaiana",
    description: "Pechuga de pollo con salsa agridulce y piña asada.",
    price: 29.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Trucha al ajillo",
    description: "Trucha fresca preparada al ajillo con hierbas y limón.",
    price: 27.7,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES","PESCADOS"],
  },
  {
    name: "Trucha gratinada",
    description: "Trucha asada con queso gratinado y especias mediterráneas.",
    price: 29,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES","PESCADOS"],
  },
  {
    name: "Picada",
    description: "Exquisita picada de carnes con acompañamientos variados.",
    price: 35.5,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES"],
  },
  {
    name: "Picada Don Chily",
    description:
      "Generosa picada con una selección premium de carnes y quesos.",
    price: 57,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","CARNES","OTROS"],
  },
  {
    name: "Ensalada Doña Florinda",
    description:
      "Ensalada fresca con ingredientes gourmet y aderezo exclusivo.",
    price: 19.9,
    img: "https://images.pexels.com/photos/4551907/pexels-photo-4551907.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    available: true,
    stock: 10,
    category: ["PARRILLA GOURMET","VEGETARIANOS","ENSALADAS"],
  },
];
