export const ordersSeed = [
  {
    id: "1",
    date: "2024-07-05T05:30:11.740Z",
    shipping: 5,
    price: 9,
    generalDiscount: 5,
    total: 9,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "1",
        quantity: 1,
        price: 4,
        discount: 0,
        total: 4,
        deletedAt: null,
        product: {
          id: 2,
          name: "Porciones papa francesa cuatro 7",
          description:
            "Crujientes porciones de papa francesa con un toque de especias.",
          price: 4.7,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "2",
        quantity: 1,
        price: 5,
        discount: 0,
        total: 5,
        deletedAt: null,
        product: {
          id: 1,
          name: "Porciones papa criolla",
          description:
            "Deliciosas porciones de papa criolla con un toque especial.",
          price: 4.7,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: true,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "2",
    date: "2024-07-05T05:31:16.544Z",
    shipping: 5,
    price: 19,
    generalDiscount: 5,
    total: 14,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "3",
        quantity: 1,
        price: 4,
        discount: 0,
        total: 4,
        deletedAt: null,
        product: {
          id: 3,
          name: "Porciones arroz chorizo de cerdo 6",
          description:
            "Sabroso arroz acompañado de chorizo de cerdo, una combinación perfecta.",
          price: 6,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "4",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "3",
    date: "2024-07-05T05:32:14.121Z",
    shipping: 5,
    price: 39,
    generalDiscount: 5,
    total: 34,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "5",
        quantity: 2,
        price: 12,
        discount: 0,
        total: 24,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "6",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 6,
          name: "Porciones pollo desmechado 8",
          description:
            "Pollo desmechado sazonado y cocinado a la perfección, irresistible.",
          price: 8,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "4",
    date: "2024-07-05T05:32:47.871Z",
    shipping: 5,
    price: 39,
    generalDiscount: 5,
    total: 34,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "7",
        quantity: 2,
        price: 12,
        discount: 0,
        total: 24,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "8",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 6,
          name: "Porciones pollo desmechado 8",
          description:
            "Pollo desmechado sazonado y cocinado a la perfección, irresistible.",
          price: 8,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "5",
    date: "2024-07-05T05:33:01.111Z",
    shipping: 5,
    price: 39,
    generalDiscount: 5,
    total: 34,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "9",
        quantity: 2,
        price: 12,
        discount: 0,
        total: 24,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "10",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 6,
          name: "Porciones pollo desmechado 8",
          description:
            "Pollo desmechado sazonado y cocinado a la perfección, irresistible.",
          price: 8,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "6",
    date: "2024-07-05T05:33:16.875Z",
    shipping: 5,
    price: 39,
    generalDiscount: 5,
    total: 34,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "11",
        quantity: 2,
        price: 12,
        discount: 0,
        total: 24,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "12",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 6,
          name: "Porciones pollo desmechado 8",
          description:
            "Pollo desmechado sazonado y cocinado a la perfección, irresistible.",
          price: 8,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "7",
    date: "2024-07-05T05:33:54.593Z",
    shipping: 5,
    price: 25,
    generalDiscount: 5,
    total: 20,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "13",
        quantity: 1,
        price: 10,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "14",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 9,
          name: "Porciones ejote 2.9",
          description:
            "Ejotes frescos y nutritivos, una opción saludable y deliciosa.",
          price: 2.9,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "8",
    date: "2024-07-05T05:34:07.339Z",
    shipping: 5,
    price: 25,
    generalDiscount: 5,
    total: 20,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "15",
        quantity: 1,
        price: 10,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "16",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 9,
          name: "Porciones ejote 2.9",
          description:
            "Ejotes frescos y nutritivos, una opción saludable y deliciosa.",
          price: 2.9,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "9",
    date: "2024-07-05T05:34:46.067Z",
    shipping: 6,
    price: 30,
    generalDiscount: 5,
    total: 25,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "17",
        quantity: 1,
        price: 15,
        discount: 0,
        total: 15,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "18",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 12,
          name: "Jugos naturales",
          description: "Refrescantes jugos naturales recién exprimidos.",
          price: 7,
          imgName: null,
          img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
  {
    id: "10",
    date: "2024-07-05T05:34:57.453Z",
    shipping: 6,
    price: 30,
    generalDiscount: 5,
    total: 25,
    status: "Pendiente",
    deletedAt: null,
    details: [
      {
        id: "19",
        quantity: 1,
        price: 15,
        discount: 0,
        total: 15,
        deletedAt: null,
        product: {
          id: 5,
          name: "Porciones carne desmechada 8.5",
          description:
            "Tierna carne desmechada preparada con ingredientes frescos y naturales.",
          price: 8.5,
          imgName: null,
          img: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
      {
        id: "20",
        quantity: 2,
        price: 5,
        discount: 0,
        total: 10,
        deletedAt: null,
        product: {
          id: 12,
          name: "Jugos naturales",
          description: "Refrescantes jugos naturales recién exprimidos.",
          price: 7,
          imgName: null,
          img: "https://images.pexels.com/photos/3230214/pexels-photo-3230214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          isPopular: false,
          stock: 10,
          isDeleted: false,
        },
      },
    ],
  },
];
